### ISSUE TITLE
Investigate Logging

### ISSUE THREAD

**Issue by diemonster** [quintilesims/terraform-eks#5]
Logging via Cloudwatch and Cloudtrail is apparently "integrated" with EKS, but there is little documentation on what that means. How do users gain access to logs, and is there additional configuration needed?

Additionally, we would like to enable Splunk logging for EKS clusters, which would likely require using Lambda + a Kinesis stream.

This issue tracks:
- [x] Investigate EKS logging integration with Cloudwatch / Cloudtrail, detail how it works and where to find it.

- [x] Investigate if we need to extend default logging
- [x] Document how to best access logs

~~- [ ] Investigate porting Layer0 lambda + kinesis stream config from Layer0 to EKS (cc @sesh-kebab )~~

**Comment by nehayward** [comment]
* Cloudtrail Is setup [automatically](https://docs.aws.amazon.com/eks/latest/userguide/logging-using-cloudtrail.html) it shows the cloud in event history.
<img width="1392" alt="screen shot 2018-06-11 at 12 03 50 pm" src="https://user-images.githubusercontent.com/6733030/41251681-8aa34732-6d6f-11e8-887e-0a21ee5b274d.png">

* "You can use CloudWatch Logs to view logs from your Kubernetes masters, and you can use CloudTrail to view logs on API activity to the Amazon EKS service endpoint. Personal Considerations"
[source](https://proj4spes.github.io/cloud/2018/01/03/EKS-kubernetes-on-AWS/) ^ **looking into this**

**Comment by diemonster** [comment]
@nehayward what about logs from k8s pods?

**Comment by nehayward** [comment]
@diemonster I'm looking into that now, I don't think there is a way to view that in AWS out of the box. I believe this is [one option](https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/02-path-working-with-clusters/204-cluster-logging-with-EFK), still investigating.

**Comment by nehayward** [comment]
# EKS Logging Setup

Currently there are not any out-of-box solution to view Kubernetes logs on AWS. However, it's integrated with [Cloudtrail](https://docs.aws.amazon.com/eks/latest/userguide/logging-using-cloudtrail.html) and there are third party services to view logs, like [Datadog](https://www.datadoghq.com/blog/announcing-eks/). We can leverage existing open source tools like fluentd and elastic search to send all of the container logs, a detailed a approach is listed below.

## Bootstrap EKS + Logging

![Design](https://user-images.githubusercontent.com/6733030/41434180-bac0e250-6fcf-11e8-8cda-bfd85dc51181.png)

The standard amongst most of these tools is [fluentd](https://www.fluentd.org), a data collector for unified logging, we will utilize fluentd to send our logs to elastics search.

1. During the setup of a new EKS cluster we could create a new ES in the AWS dashboard or via the [AWS terraform provider](https://www.terraform.io/docs/providers/aws/r/elasticsearch_domain.html). We will need to setup this up and take note of the aws_elasticsearch_domain.es.endpoint.

2. After the ES is available and the EKS cluster is up we need to replace the following ENV variable values `AWS_REGION`, `AWS_ELASTICSEARCH_URL`, `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`. We can do this manually by editing the file listed below or have terraform automate this and then do a local exec of `kubectl create -f fluentd-aws-es-daemonset.yml`.

3. The logs should then begin streaming, an example can be [viewed here](https://search-kubernetes-logs-53a7pfhmiqughp7jcaidlh7fuy.us-west-2.es.amazonaws.com/_plugin/kibana/app/kibana#/discover?_g=()&_a=(columns:!(_source),index:'logstash-*',interval:auto,query:(match_all:()),sort:!('@timestamp',desc)))


example file of `fluend-aws-es-daemonset.yml`

```yaml  
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: fluentd-logging
    kubernetes.io/cluster-service: "true"
  name: fluentd-elasticsearch
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      kubernetes.io/cluster-service: "true"
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        k8s-app: fluentd-logging
        kubernetes.io/cluster-service: "true"
      name: fluentd-elasticsearch
      namespace: kube-system
    spec:
      containers:
      - env:
        - name: AWS_REGION
          value: us-west-2
        - name: AWS_ELASTICSEARCH_URL
          value: {Replace}
        - name: AWS_ACCESS_KEY_ID
          value: {Replace}
        - name: AWS_SECRET_ACCESS_KEY
          value: {Replace}
        image: cheungpat/fluentd-elasticsearch-aws:1.22
        imagePullPolicy: IfNotPresent
        name: fluentd-elasticsearch
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
      restartPolicy: Always
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      volumes:
      - hostPath:
          path: /var/log
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
        name: varlibdockercontainers
```

### Caveats

```go  
  - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
```

It's important to note that your container is outputting logs to one of these paths. These are standard and if your app is using something else these may have to be modified.

## Alternatives

- [Datadog](https://www.datadoghq.com/blog/announcing-eks/)
- [Sumologic](https://help.sumologic.com/Send-Data/Applications-and-Other-Data-Sources/Amazon_EKS/Collect_Logs_for_Amazon_EKS)

### Resources

- [Blog Post on FluentD Setup](https://medium.com/@while1eq1/logging-to-aws-elasticsearch-service-from-kubernetes-855ad0959251)
